### ISSUE TITLE
Weird page formatting in Firefox on macOS Sequoia

### ISSUE THREAD

**Issue by e14tech** [minisat0shi/minisatoshi.cash#7]
![Screenshot 2024-09-24 at 19-26-38 minisatoshi cash It's up to us](https://github.com/user-attachments/assets/64920ee8-7395-42d0-a9e0-cd4fe7cac829)
![Screenshot 2024-09-24 at 19-26-54 minisatoshi cash It's up to us](https://github.com/user-attachments/assets/602b8f9a-c7f7-43d9-a763-fb3a9cf23817)

**Comment by e14tech** [comment]
Title bar is the same color as the text when viewing the fork map page.
Text is all weird on the resources page.

**Comment by minisat0shi** [comment]
Navbar issue fixed [https://github.com/minisat0shi/minisatoshi.cash/commit/1d6ee661817cfc8034d2921912f8ca858547fd5f](url)

**Comment by minisat0shi** [comment]
All fixed now per [https://github.com/minisat0shi/minisatoshi.cash/commit/f5e18540e228d9eacc2549f2b7fcb96861883e60](url)
